name: CI
on:  [workflow_dispatch, pull_request, push]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
      - name: Run FedericoCarboni/setup-ffmpeg
      - uses: fastai/workflows/nbdev-ci@master
